
package com.xiaoshabao.wechat.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-08T21:34:52.146+08:00
 * Generated source version: 3.1.7
 * 
 */
public final class TokenServerWS_TokenServerWSImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.webservice.wechat.xiaoshabao.com/", "TokenServerWSImplService");

    private TokenServerWS_TokenServerWSImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TokenServerWSImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TokenServerWSImplService ss = new TokenServerWSImplService(wsdlURL, SERVICE_NAME);
        TokenServerWS port = ss.getTokenServerWSImplPort();  
        
        {
        System.out.println("Invoking getToken...");
        java.lang.Integer _getToken_arg0 = null;
        com.xiaoshabao.wechat.webservice.AccessToken _getToken__return = port.getToken(_getToken_arg0);
        System.out.println("getToken.result=" + _getToken__return);


        }

        System.exit(0);
    }

}
